### ISSUE TITLE
Crash when using JobDSL's archiveArtifacts()

### ISSUE THREAD

**Issue by tommyd3mdi** [ghale/gradle-jenkins-plugin#69]
When I setup an archiveArtifacts publisher, similar to this

    jenkins {
        templates {
            foo {
                dsl {
                    publishers {
                        archiveArtifacts('**/*.jar')
                    }
                }
            }
        }
    }

then Gradle crashes inside the JobDSL plugin with

    org.gradle.api.GradleScriptException: A problem occurred evaluating root project 'project'.
    	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
    	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl$1.run(DefaultScriptPluginFactory.java:148)
    	at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:72)
    	at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:153)
    	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:38)
    	at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:25)
    	at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
    	at org.gradle.configuration.project.LifecycleProjectEvaluator.evaluate(LifecycleProjectEvaluator.java:55)
    	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:499)
    	at org.gradle.api.internal.project.AbstractProject.evaluate(AbstractProject.java:86)
    	at org.gradle.execution.TaskPathProjectEvaluator.configure(TaskPathProjectEvaluator.java:35)
    	at org.gradle.configuration.DefaultBuildConfigurer.configure(DefaultBuildConfigurer.java:33)
    	at org.gradle.initialization.DefaultGradleLauncher$2.run(DefaultGradleLauncher.java:125)
    	at org.gradle.internal.Factories$1.create(Factories.java:22)
    	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
    	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
    	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:122)
    	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
    	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
    	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
    	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
    	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
    	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
    	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
    	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
    	at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
    	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
    	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
    	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
    	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:77)
    	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:47)
    	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
    	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
    	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
    	at org.gradle.util.Swapper.swap(Swapper.java:38)
    	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:66)
    	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:71)
    	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
    	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
    	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
    	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
    	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
    	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
    Caused by: java.lang.NullPointerException: Cannot invoke method isOlderThan() on null object
    	at javaposse.jobdsl.dsl.helpers.publisher.PublisherContext$_archiveArtifacts_closure3.doCall(PublisherContext.groovy:115)
    	at javaposse.jobdsl.dsl.helpers.publisher.PublisherContext$_archiveArtifacts_closure3.doCall(PublisherContext.groovy)
    	at javaposse.jobdsl.dsl.helpers.publisher.PublisherContext.archiveArtifacts(PublisherContext.groovy:108)
    	at javaposse.jobdsl.dsl.helpers.publisher.PublisherContext$archiveArtifacts.callCurrent(Unknown Source)
    	at javaposse.jobdsl.dsl.helpers.publisher.PublisherContext.archiveArtifacts(PublisherContext.groovy:128)
    	at javaposse.jobdsl.dsl.helpers.publisher.PublisherContext.archiveArtifacts(PublisherContext.groovy)
    	at build_7xpt8m36ezzxm5s7hriof7gxk$_run_closure2$_closure11$_closure16$_closure20$_closure22.doCall(/my/project/build.gradle:138)
    	at build_7xpt8m36ezzxm5s7hriof7gxk$_run_closure2$_closure11$_closure16$_closure20$_closure22.doCall(/my/project/build.gradle)
    	at javaposse.jobdsl.dsl.ContextHelper.executeInContext(ContextHelper.groovy:14)
    	at javaposse.jobdsl.dsl.ContextHelper$executeInContext.call(Unknown Source)
    	at javaposse.jobdsl.dsl.Job.publishers(Job.groovy:521)
    	at build_7xpt8m36ezzxm5s7hriof7gxk$_run_closure2$_closure11$_closure16$_closure20.doCall(/my/project/build.gradle:137)
    	at com.terrafolio.gradle.plugins.jenkins.dsl.JobDSLSupport.evaluateDSL(JobDSLSupport.groovy:44)
    	at com.terrafolio.gradle.plugins.jenkins.dsl.DSLSupport$evaluateDSL$0.call(Unknown Source)
    	at com.terrafolio.gradle.plugins.jenkins.dsl.JenkinsJobTemplate.dsl(JenkinsJobTemplate.groovy:48)
    	at build_7xpt8m36ezzxm5s7hriof7gxk$_run_closure2$_closure11$_closure16.doCall(/my/project/build.gradle:128)
    	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
    	at org.gradle.api.internal.AbstractNamedDomainObjectContainer.create(AbstractNamedDomainObjectContainer.java:59)
    	at org.gradle.api.internal.AbstractNamedDomainObjectContainer.create(AbstractNamedDomainObjectContainer.java:52)
    	at org.gradle.api.internal.NamedDomainObjectContainerConfigureDelegate._configure(NamedDomainObjectContainerConfigureDelegate.java:39)
    	at org.gradle.api.internal.ConfigureDelegate.invokeMethod(ConfigureDelegate.java:73)
    	at build_7xpt8m36ezzxm5s7hriof7gxk$_run_closure2$_closure11.doCall(/my/project/build.gradle:127)
    	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
    	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
    	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:91)
    	at org.gradle.api.internal.AbstractNamedDomainObjectContainer.configure(AbstractNamedDomainObjectContainer.java:68)
    	at org.gradle.api.internal.AbstractNamedDomainObjectContainer.configure(AbstractNamedDomainObjectContainer.java:24)
    	at org.gradle.api.NamedDomainObjectContainer$configure$0.call(Unknown Source)
    	at com.terrafolio.gradle.plugins.jenkins.dsl.JenkinsConfiguration.templates(JenkinsConfiguration.groovy:33)
    	at build_7xpt8m36ezzxm5s7hriof7gxk$_run_closure2.doCall(/my/project/build.gradle:126)
    	at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:67)
    	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:130)
    	at org.gradle.util.ConfigureUtil.configure(ConfigureUtil.java:91)
    	at org.gradle.util.ConfigureUtil$configure.call(Unknown Source)
    	at com.terrafolio.gradle.plugins.jenkins.dsl.JenkinsConfigurationConvention.jenkins(JenkinsConfigurationConvention.groovy:13)
    	at com.terrafolio.gradle.plugins.jenkins.dsl.JenkinsConfigurationConvention.invokeMethod(JenkinsConfigurationConvention.groovy)
    	at org.gradle.api.internal.BeanDynamicObject$GroovyObjectAdapter.invokeMethod(BeanDynamicObject.java:275)
    	at org.gradle.api.internal.BeanDynamicObject.invokeMethod(BeanDynamicObject.java:127)
    	at org.gradle.api.internal.plugins.DefaultConvention$ExtensionsDynamicObject.invokeMethod(DefaultConvention.java:212)
    	at org.gradle.api.internal.CompositeDynamicObject.invokeMethod(CompositeDynamicObject.java:150)
    	at org.gradle.groovy.scripts.BasicScript.methodMissing(BasicScript.java:79)
    	at build_7xpt8m36ezzxm5s7hriof7gxk.run(/my/project/build.gradle:75)
    	at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:91)
    	... 58 more

An update to a newer version of JobDSL could remedy this issue, because the code that crashes (https://github.com/jenkinsci/job-dsl-plugin/blob/job-dsl-1.34/job-dsl-core/src/main/groovy/javaposse/jobdsl/dsl/helpers/publisher/PublisherContext.groovy#L115) is gone in more recent versions, because the jobdsl-plugin has raised their minimum Jenkins version requirement, however, I suspect this could be more of a general problem because the Gradle JobDSL plugin does not properly set the property `jenkinsVersion` on the `jobManagement` component that *might* be used elsewhere as well.

**Comment by foeser** [comment]
Hey,

I ran into the same problem. What is your workaround?

Thanks in advice,
Florian

**Comment by foeser** [comment]
Manipulating the XML is still working :)

`configure { node ->
                            node / 'publishers' / 'hudson.tasks.ArtifactArchiver' {
                                artifacts('xxx')
                                latestOnly('false')
                                allowEmptyArchive('false')      
                          [...]
                             }  
             } `
